### ISSUE TITLE
Certain props are not available

### ISSUE THREAD

**Issue by alabastor95** [kcsujeet/sl-vue-tree-next#1]
It seems that `mutliselectKey` prop is not assignable. I am not sure, about this, but I think `SlVueTreeNext.vue.d.ts` file has the assignable props. If this is correct, `scrollAreaHeight` and `maxScrollSpeed` are not assignable either. 
Although `edgeSize` is assignable, it does not seem to do anything.

**Comment by kcsujeet** [comment]
Thanks for bringing up the issue. I've exposed more props and fixed keyboard control issues in [this](https://github.com/kcsujeet/sl-vue-tree-next/commit/94884fe9d7d095318d7a25e9004e29c95520ff95) commit. New changes should be available in `v0.0.11`.

In my testing, `edgeSize` seems to be working well. Let me know if you find any issues. Glad to resolve them. : )

**Comment by alabastor95** [comment]
Thank you for your help!
