### ISSUE TITLE
Moving multiple layers

### ISSUE THREAD

**Issue by alabastor95** [kcsujeet/sl-vue-tree-next#4]
When moving multiple layers, it duplicates child nodes at the location of parent nodes. As it is difficult do clearly describe I will add a video recording. 

Cause of this: the program moves each highlighted node to the target location, ignoring that it has been already moved via its parent.

Suggestion for avoiding this: when moving multiple nodes check for each node weather its parent moved. If parent moved, ignore the child's movement.

[Screencast from 2024-03-14 11:44:38.webm](https://github.com/kcsujeet/sl-vue-tree-next/assets/24634761/522657a5-a354-4e2f-b82b-9463f49edf43)

**Comment by alabastor95** [comment]
Here is a little solution for filtering out contents that already have parent. Not my best work, but maybe it can help:

```
function filterOutChildrenNodesWithParents(nodeArray){
    if(nodeArray.length == 0){
        return nodeArray;
    }
    let filteredPathArray = [nodeArray[0].path];
    nodeArray.forEach((node)=>{
        let isAddNode = true;
        for(let path of filteredPathArray){
            if(isInTheSamePath(node.path, path) || path == node.path){
                isAddNode = false;
                break;
            }
        }
        if(isAddNode){
            filteredPathArray.push(node.path);
        }
    })
    return filteredPathArray;
}

function isInTheSamePath(pathArray1, pathArray2){
    let isSamePath = true;
    let longer = pathArray1;
    let shorter = pathArray2;
    if(pathArray1.length<pathArray2.length){
        longer = pathArray2;
        shorter = pathArray1;
    }
    for(let i=0; i<shorter.length; i++){
        if(shorter[i]!=longer[i]){
            isSamePath = false;
            break;
        }
    }
    return isSamePath;
}
```

**Comment by kcsujeet** [comment]
Fixed in https://github.com/kcsujeet/sl-vue-tree-next/pull/7 ... new version `0.0.13`
