### ISSUE TITLE
Whole data property is overridden on updateNode

### ISSUE THREAD

**Issue by alabastor95** [kcsujeet/sl-vue-tree-next#5]
When using `updateNode()` to override `data` of a node, it overrides the whole `data`, instead of only a specific part of it.

Example code:
```vue3
    slVueTree.value.updateNode({path:selectedNode.path, patch:{data: {renameNode : true}}});
    console.log(slVueTree.value.getNode(selectedNode.path));
    slVueTree.value.updateNode({path:selectedNode.path, patch:{data: {realLocation : true}}});
    console.log(slVueTree.value.getNode(selectedNode.path));
```

Based on the console messages, the `data` field looses the `renameNode` field when adding `realLocation`.

**Comment by alabastor95** [comment]
If someone has the same problem, it is easy to solve it by including the previous values for the given node. A quick example:

```
function changeDataField(node, newDataJSON){
    for(var key in newDataJSON){
        node.data[key] = newDataJSON[key];
    }
    slVueTree.value.updateNode({path:node.path, patch : { data : node.data}});
}
```

**Comment by kcsujeet** [comment]
Fixed in https://github.com/kcsujeet/sl-vue-tree-next/pull/7 ... new version `0.0.13`
