### ISSUE TITLE
Demo Problem

### ISSUE THREAD

**Issue by alabastor95** [kcsujeet/sl-vue-tree-next#8]
The demos are not working:

![Screenshot from 2024-03-19 10-21-37](https://github.com/kcsujeet/sl-vue-tree-next/assets/24634761/c0b65308-4f43-4242-9f24-a6e86e76ad46)

https://kcsujeet.github.io/sl-vue-tree-next/demo/index.html

**Comment by kcsujeet** [comment]
Fixed in 5c7001038f4e4021ef562a41f077ab14222a5046
